# Define a default and consistent copyright string, available as {{ .Site.Copyright }}
copyright = '&copy; {{ now.Year }} {{ .Site.Title }}'

# Default language to use for site i18n
defaultContentLanguage = 'en'

# Disable the meta generator entry
disableHugoGeneratorInject = true

# Disable kinds we do not use
disableKinds = ['rss', 'sitemap', 'taxonomy', 'term']
